"""Build integrated_prefix.gdl — the LEGACY prefix-KIF artifact.

Prefix KIF is an OUTDATED dialect, kept only because the step
fragments are still written in it and some older tooling reads it.
It is hard for a human to read and nobody should have to. The
OFFICIAL description is the infix file docs/gdl/integrated.gdl,
produced from this one by docs/gdl/build_integrated.py.

Concatenates the 11 step fragments and de-duplicates top-level
clauses. Each step file is independent (re-declares helpers from
prior steps for self-containedness); the integrated file collapses
duplicates so a reasoner loads ONE canonical version.

Usage — ALWAYS run both, in this order, so the two files stay
consistent:

    python3 docs/gdl/build_integrated_prefix.py > docs/gdl/integrated_prefix.gdl
    python3 docs/gdl/build_integrated.py
"""

import os
import sys

# Promote the test parser into the build path.
sys.path.insert(0, os.path.join(
    os.path.dirname(__file__), '..', '..', 'tests'))
from test_gdl_step1 import _tokenize, _parse_all, _strip_comments

STEP_FILES = [
    'step1_kings_queens.gdl',
    'step2_kings_queens_pawns.gdl',
    'step3_add_rook.gdl',
    'step4_add_knight.gdl',
    'step5_add_bishop.gdl',
    'step6_add_boulder.gdl',
    'step7_add_queen_actions.gdl',
    'step8_add_knight_jump_capture_invuln.gdl',
    'step9_add_bishop_reactive_capture.gdl',
    'step10_add_repetition_rule.gdl',
    'step11_add_tiny_endgame_rule.gdl',
]


def _normalise(form):
    """Convert a parsed form back to a normalised string for
    deduplication."""
    if isinstance(form, str):
        return form
    return '(' + ' '.join(_normalise(c) for c in form) + ')'


def main():
    here = os.path.dirname(__file__)
    seen = set()
    out_clauses = []

    for filename in STEP_FILES:
        path = os.path.join(here, filename)
        if not os.path.exists(path):
            print(f"; MISSING {filename}", file=sys.stderr)
            continue
        with open(path) as f:
            text = f.read()
        forms = _parse_all(_tokenize(_strip_comments(text)))
        section_added = 0
        for form in forms:
            key = _normalise(form)
            if key in seen:
                continue
            seen.add(key)
            out_clauses.append((filename, key))
            section_added += 1
        print(f"; {filename}: {section_added} unique clauses",
              file=sys.stderr)

    # Emit.
    print('; ============================================================')
    print('; INTEGRATED GDL — LEGACY prefix-KIF dialect. DO NOT READ THIS.')
    print(';')
    print('; Prefix KIF is an OUTDATED dialect and is hard to read. The')
    print('; OFFICIAL description of this game is the infix file')
    print(';     docs/gdl/integrated.gdl')
    print('; which is generated from this one and says exactly the same')
    print('; thing in a readable dialect. Read that instead. This file')
    print('; exists only to feed the infix build and older tooling.')
    print(';')
    print('; All 11 fragments deduplicated, grouped by clause family')
    print('; (issue #166). Generated by build_integrated_prefix.py.')
    print('; Source of truth = the individual step files. After changing')
    print('; a step file re-run BOTH build scripts (issue #190):')
    print(';   python3 docs/gdl/build_integrated_prefix.py > docs/gdl/integrated_prefix.gdl')
    print(';   python3 docs/gdl/build_integrated.py')
    print('; ============================================================')
    print()

    # Group clauses by FAMILY (head predicate; init facts by their
    # inner predicate) so that a family declared across several steps
    # with partial overlap is emitted in ONE place. Without this,
    # first-seen dedup scattered families — e.g. steps 6+ declare the
    # turn-number chain (succ 1..10) while step 10 alone adds
    # (succ 0 1) for repetition counts, which stranded that single
    # fact in step 10's section (issue #166). Groups appear at their
    # first-seen position and clauses keep first-seen order within a
    # group (GDL semantics are order-independent; preserving
    # within-family order keeps recursive definitions base-case
    # first). Provenance lives in the step files, which are the
    # source of truth.
    def family(clause):
        toks = clause.replace('(', ' ( ').replace(')', ' ) ').split()
        # toks like: ( <= ( head ... | ( init ( pred ... | ( role white
        try:
            if toks[1] == '<=':
                head = toks[3] if toks[2] == '(' else toks[2]
                if head in ('init', 'next'):
                    return (head, toks[5] if toks[4] == '(' else toks[4])
                if head == 'legal':
                    # group by the action functor: (legal ?p (act ...))
                    i = toks.index('legal')
                    rest = toks[i + 1:]
                    for j, t in enumerate(rest):
                        if t == '(':
                            return ('legal', rest[j + 1])
                    return ('legal', rest[0])
                return (head,)
            if toks[1] == 'init':
                return ('init', toks[3] if toks[2] == '(' else toks[2])
            return (toks[1],)
        except (IndexError, ValueError):
            return (clause,)

    groups = []          # list of family keys, first-seen order
    grouped = {}         # family -> [clauses]
    for _src, clause in out_clauses:
        key = family(clause)
        if key not in grouped:
            grouped[key] = []
            groups.append(key)
        grouped[key].append(clause)

    def natural_key(clause):
        import re as _re
        return [int(t) if t.isdigit() else t
                for t in _re.split(r'(\d+)', clause)]

    for key in groups:
        print()
        print(f'; ---- {" ".join(str(k) for k in key)} ----')
        # Ground facts (no variables) sort naturally within their
        # family — e.g. (succ 0 1) leads the chain; rules keep
        # first-seen order (base cases stay before recursive cases).
        facts = sorted((c for c in grouped[key] if '?' not in c),
                       key=natural_key)
        rules = [c for c in grouped[key] if '?' in c]
        for clause in facts + rules:
            print(clause)


if __name__ == '__main__':
    main()
