"""Build the integrated GDL file by concatenating the 11 step
fragments and de-duplicating top-level clauses.

Each step file is independent (re-declares helpers from prior
steps for self-containedness). The integrated file collapses
duplicates so a reasoner loads ONE canonical version.

Usage:
    python3 docs/gdl/build_integrated.py > docs/gdl/integrated.gdl
"""

import os
import sys

# Promote the test parser into the build path.
sys.path.insert(0, os.path.join(
    os.path.dirname(__file__), '..', '..', 'tests'))
from test_gdl_step1 import _tokenize, _parse_all, _strip_comments

STEP_FILES = [
    'step1_kings_queens.gdl',
    'step2_kings_queens_pawns.gdl',
    'step3_add_rook.gdl',
    'step4_add_knight.gdl',
    'step5_add_bishop.gdl',
    'step6_add_boulder.gdl',
    'step7_add_queen_actions.gdl',
    'step8_add_knight_jump_capture_invuln.gdl',
    'step9_add_bishop_reactive_capture.gdl',
    'step10_add_repetition_rule.gdl',
    'step11_add_tiny_endgame_rule.gdl',
]


def _normalise(form):
    """Convert a parsed form back to a normalised string for
    deduplication."""
    if isinstance(form, str):
        return form
    return '(' + ' '.join(_normalise(c) for c in form) + ')'


def main():
    here = os.path.dirname(__file__)
    seen = set()
    out_clauses = []

    for filename in STEP_FILES:
        path = os.path.join(here, filename)
        if not os.path.exists(path):
            print(f"; MISSING {filename}", file=sys.stderr)
            continue
        with open(path) as f:
            text = f.read()
        forms = _parse_all(_tokenize(_strip_comments(text)))
        section_added = 0
        for form in forms:
            key = _normalise(form)
            if key in seen:
                continue
            seen.add(key)
            out_clauses.append((filename, key))
            section_added += 1
        print(f"; {filename}: {section_added} unique clauses",
              file=sys.stderr)

    # Emit.
    print('; ============================================================')
    print('; INTEGRATED GDL — all 11 fragments deduplicated.')
    print(';')
    print('; Generated by docs/gdl/build_integrated.py.')
    print('; Source of truth = the individual step files; this is a')
    print('; convenience artifact for reasoner loading. Re-run the')
    print('; build script whenever a step file changes.')
    print('; ============================================================')
    print()

    current_file = None
    for src_file, clause in out_clauses:
        if src_file != current_file:
            print()
            print(f'; ---- from {src_file} ----')
            current_file = src_file
        print(clause)


if __name__ == '__main__':
    main()
