"""Build docs/gdl/integrated_infix.gdl — the modern infix-HRF
rendering of the integrated ruleset.

Reads the prefix-KIF `integrated.gdl` (which build_integrated.py
produces from the 11 step fragments) and converts it via
src/ggp/infix.py. Re-run after any step-file change:

    python3 docs/gdl/build_integrated.py > docs/gdl/integrated.gdl
    python3 docs/gdl/build_integrated_infix.py

The prefix step files remain the SOURCE OF TRUTH; both integrated
files are generated artifacts.
"""

import os
import sys

sys.path.insert(0, os.path.join(
    os.path.dirname(__file__), '..', '..', 'src'))

from ggp.infix import convert_text

HERE = os.path.dirname(__file__)
PREFIX_PATH = os.path.join(HERE, 'integrated.gdl')
INFIX_PATH = os.path.join(HERE, 'integrated_infix.gdl')

HEADER = """\
============================================================
INTEGRATED GDL — infix HRF dialect (ggp.stanford.edu / Epilog).

Generated by docs/gdl/build_integrated_infix.py from the
prefix-KIF integrated.gdl (itself generated from the 11 step
fragments by build_integrated.py). Do not edit by hand — edit
the step files and re-run both build scripts.

Conversion notes:
- (or A B) bodies were expanded into one rule per branch.
- (= ?x c) conjuncts were resolved by constant substitution.
Both transformations are semantics-preserving.
============================================================\
"""


def main():
    with open(PREFIX_PATH) as f:
        prefix_text = f.read()
    infix_text = convert_text(prefix_text, header_comment=HEADER)
    with open(INFIX_PATH, 'w') as f:
        f.write(infix_text)
    n_statements = sum(
        1 for line in infix_text.splitlines()
        if line.strip() and not line.strip().startswith('%'))
    print(f'wrote {INFIX_PATH}: {n_statements} statements')


if __name__ == '__main__':
    main()
